//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToken
    {
        public string CreatedBy { get; set; }
        public System.DateTime ExpireTime { get; set; }
        public string Token { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string TokenType { get; set; }
        public string UserName { get; set; }
    }
}
